### PR TITLE
quote dump!

### PR DESCRIPTION
**Pull request by RayDeeUx**
as promised earlier in the discord

—ery

### CODE REVIEW

**Comment by vooxal** [comment]
Huh i like the fixes here. I would recommend taking it from (twemoji)[https://github.com/twitter/twemoji/blob/master/assets/svg/1f1e6.svg] but ill do that myself since its a pain in the ass

**Comment by vooxal** [comment]
Ok another thing, move the `quotes` array and the `quote` element out of the setInterval. The reason why setInterval has a weird pause is since it doesn't run the code the first loop. So i would set the text first, then change it with set interval

**Comment by vooxal** [comment]
Ok this is a less of a band-aid fix to the empty screen. Read more on self invoking functions [here](https://blog.mgechev.com/2012/08/29/self-invoking-functions-in-javascript-or-immediately-invoked-function-expression/)

**Comment by vooxal** [comment]
can you test?

**Comment by DTRW919** [comment]
What is gonna happen with this

**Comment by RayDeeUx** [comment]
gonna close since voxal and i already swapped to arrow key-based advancing quotes

**Pull request closed without merging**
