### PR TITLE
add quotes

### PR DESCRIPTION
**Pull request by RayDeeUx**
—ery

### CODE REVIEW

**Comment by vooxal** [comment]
Please review my changes.

**Comment by DTRW919** [comment]
Looks good, but I would remove the Wix one or else idiots would call the makers of the site nerds for using Wix lol

**Comment by DTRW919** [comment]
Tbh I like looking at pull requests and checking em idk why if ya want me to stop just tell me and I'll stop and shut up <3

**Comment by vooxal** [comment]
Looks good now @RayDeeUx, take a look at it.

**Comment by vooxal** [comment]
> Looks good, but I would remove the Wix one or else idiots would call the makers of the site nerds for using Wix lol

you can't use wix for the randomized stuff lmao. also the site isn't `furfsky.wixsite.com` its `github.io` which is for foss projects.

**Comment by DTRW919** [comment]
I said they were idiots, I doubt idiots would look at URLs cuz theyre idiots :p but you have a point

**Review by vooxal — CHANGES_REQUESTED** [review]
You just redoed my changes. Please don't since that makes everything messy and doesn't belong in my code.

**Comment by DTRW919** [comment]
So what's happening with this request, will it happen?

**Comment by vooxal** [comment]
> So what's happening with this request, will it happen?

After the changes requested are done, i will merge

**Comment by DTRW919** [comment]
alrighty

**Comment by vooxal** [comment]
You didn't make any changes lmao.

**Review by vooxal — CHANGES_REQUESTED** [review]
Please remove the previous commit, it makes everything emssy

**Comment by RayDeeUx** [comment]
RE: weird initial empty frame

Maybe we edit line 63 in index.html (homepage index) with some filler text between the <h1></h1> tags as a Band-Aid type of fix?

**Comment by vooxal** [comment]
Looks good, merging

**Pull request merged**
