### PR TITLE
QOL Change for handling Navigation Menu

### PR DESCRIPTION
**Pull request by Owlahk**
Decouple config for navigation menu links and images, add it to data config object. 

Replace node.innerHTML = ... with a proper node builder function. 
(setting stuff with innerHTML is an anti-pattern, should be avoided at all cost). 

Replace inline mouseover and mouseout events with a single mouseover and mouseout event listener that is hooked to the parent ul node (instead of creating multiple event listeners for each image).

### CODE REVIEW

**Comment by Owlahk** [comment]
It would be also pog to split service/helper functions to a separate file so we don't clutter the what is essentially a config file with extra stuff.

**Comment by vooxal** [comment]
I would definitely do this but i believe it would be much faster without having to construct it. I will give the LGTM signal so if ery feels its a good merge he can do it.

**Comment by Owlahk** [comment]
> I would definitely do this but i believe it would be much faster without having to construct it. 
Are you talking about innerHTML vs document.createElement ?

If so, innerHTML is slower in that regard if it's not a simple string. It has to parse the string and also create new nodes and append to dom, so it's usually more preferable to just directly create those yourself :)

**Comment by RayDeeUx** [comment]
Tested the fork on my own and things look good to go. Merging.

**Pull request merged**
