### PR TITLE
updating roles

### PR DESCRIPTION
**Pull request by Eejit43**
– gave `a` elements coloring for credits page
– updated roles for erymanthus
– removed zburger from packSubmissions as they are now a trial artist
– removed (backup?) code in `data.js`
– alphabetized people in credits

### CODE REVIEW

**Comment by Eejit43** [comment]
don't merge yet– awaiting message from gonk

**Comment by RayDeeUx** [comment]
don't alphabetize, they were ordered by role and then join date

**Comment by Eejit43** [comment]
ahhhh okay i was told to– they are organized by role, and i'll revert the ordering inside roles if needed but I think this looks much better and is simpler– plus some weren't sorted by join dates anyway.

**Comment by voxxal** [comment]
don't reorder it manually, just use `array.sort`

**Comment by RayDeeUx** [comment]
~~how about a toggle to sort alphabetically~~ voxal has organized the credits by role then join date since day 1, i genuinely don't see a reason to change that

also i personally think gonk is on a power trip right now and seems like the kind of guy who would expose my personal info if he had the resources to do so, so take his wishes re: my credit with two tons of salt and just set my role to retired

**Comment by RayDeeUx** [comment]
also the code in `data.js` is there so we can uncomment it quickly if we ever figure out how to fix quote rendering with the CSS foxscript wrote a while back, as well as some stuff that could be used again in the future. the idea is that we don't need to go on a goose chase on github to recover whatever code we need at the time

**Comment by RayDeeUx** [comment]
>plus some weren't sorted by join dates anyway.

which ones specifically? (btw by "join date" i meant the date they started under X role, not join date of the discord server. technically they're synonymous for the veteran artists like soshjam/duckiscool69, but that's about it)

**Comment by Eejit43** [comment]
to answer a lot of the stuff:

– I did do it with `array.sort` however I didn't implement it into the code, I'll do that later
– alphabetical credits organization has been approved and I think we'll do that
– in `data.js` I only removed the code that was in use other places and not part of the quote rendering thingy. check out the diff in regards to that

**Comment by RayDeeUx** [comment]
> alphabetical credits organization has been approved and I think we'll do that

:wah:

**Comment by voxxal** [comment]
archiving the repo

**Pull request closed without merging**
